portfolio/urls.py
from django.contrib import admin
from django.urls import include
from django.urls import path
from detail import myurl
from django.conf.urls.static import static

from portfolio import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include(myurl)),
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

detail/models.py
from django.db import models

# Create your models here.
class Author(models.Model):
    first_name = models.CharField(max_length=150, blank=False)
    last_name = models.CharField(max_length=150, blank=False)
    email = models.CharField(max_length=100, blank=True)

    def __str__(self):
        return self.first_name + " " + self.last_name

class Blog(models.Model):
    author = models.ForeignKey(Author, on_delete=models.CASCADE)
    title = models.CharField(max_length=100, blank=True, null=True)
    description = models.TextField(blank=True)
    image = models.FileField(upload_to="img", blank=True)
    published_date = models.DateTimeField(auto_now=True)
    publish = models.BooleanField(default=False)

    def __str__(self):
        return self.title

class AboutMe(models.Model):
    name = models.CharField(max_length=100, blank=False)
    description = models.TextField(blank=True)
    facebook_link = models.CharField(max_length=100, blank=True)
    twitter_link = models.CharField(max_length=100, blank=True)
    linkedin_link = models.CharField(max_length=100, blank=True)

class Education(models.Model):
    aboutme = models.ForeignKey(AboutMe, on_delete=models.CASCADE)
    degree_type = (("SLC", "School Leaving certificate"), ("Bachelor", "Bachelor"), ("Master", "Master"))
    degree = models.CharField(max_length=50, choices=degree_type, default="SLC")
    percentage = models.IntegerField(default=0)
    passed_year = models.DateField()


class Work(models.Model):
    title = models.CharField(max_length=100, blank=False)
    description = models.TextField(blank=True)
    image = models.FileField(upload_to='work', blank=True)
    web_link = models.CharField(max_length=100, blank=True)

    def __str__(self):
        return self.title

class Contact(models.Model):
    email = models.CharField(max_length=100, blank=True)
    full_name = models.CharField(max_length=100, blank=False)

    def __str__(self):
        return self.full_name

detail/forms.py
from django import forms

class ContactForm(forms.Form):
    name = forms.CharField(max_length=30)
    email = forms.EmailField(max_length=254)
    phone = forms.CharField(max_length=10)
    write_message = forms.BooleanField()
    message = forms.CharField(
        max_length=2000,
        widget=forms.Textarea(),
        help_text='Write here your message!'
    )
    source = forms.CharField(       # A hidden input for internal use
        max_length=50,              # tell from which page the user sent the message
        widget=forms.HiddenInput()
    )

    def clean(self):
        cleaned_data = super(ContactForm, self).clean()
        name = cleaned_data.get('name')
        email = cleaned_data.get('email')
        message = cleaned_data.get('message')
        if not name and not email:
            raise forms.ValidationError('You have to write something!')

detail/views.py
from django.http import HttpResponse
from django.shortcuts import render

# Create your views here.
from django.views.decorators.csrf import csrf_exempt

from detail.forms import ContactForm
from detail.models import Blog, Contact, Work


def index(request):
    return HttpResponse("hello this is detail index page")

def blogList(request):
    # need html template to show the bloglist
    # access the data from the model
    # pass the data to the bloglist html
    if request.method == "GET":
        data = Blog.objects.all()
        print(len(data))
        return render(request, 'detail/bloglist.html', {'bloglist':data})
    else:
        return HttpResponse("Only supports get request")

def aboutMe(request):
    return render(request, 'detail/aboutme.html')

def blogDetail(request, id):
    blog = Blog.objects.get(pk=id)
    return render(request, 'detail/blogdetail.html', {"blog": blog})

def addContact(request):
    if request.method == 'GET':
        return render(request, 'detail/contact.html')
    if request.method == 'POST':
        # get the data from the request body
        name = request.POST.get('fullname')
        email = request.POST.get('email')
        # save the data
        contact = Contact(full_name= name, email=email)
        contact.save()
        return HttpResponse("name = {}, email = {} is saved in server".format(name, email))

def myWork(request):
    # fetch all the work list from the table
    # pass the list to the template
    # retrieve
    workList = Work.objects.all()
    # pass the template
    return render(request, 'detail/mywork.html', {'data': workList})


def admin(request):
    return render(request, 'detail/admin.html')

def contactForm(request):
    if request.method == 'POST':
        form = ContactForm(request.POST)
        if form.is_valid():
            def save(self):
                data = self.cleaned_data
                # contact = Contact(email=data['email'], first_name=data['first_name'],
                #             last_name=data['last_name'], password1=data['password1'],
                #             password2=data['password2'])
                # contact.save()
            pass  # does nothing, just trigger the validation
    else:
        form = ContactForm()
    return render(request, 'detail/contactform.html', {'form': form})

detail/templates/detail/aboutme.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
    <link href="//netdna.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap.min.css" rel="stylesheet" id="bootstrap-css">
    <link href="{% static 'css/aboutme.css' %}" rel="stylesheet">
    <script src="//netdna.bootstrapcdn.com/bootstrap/3.2.0/js/bootstrap.min.js"></script>
    <script src="//code.jquery.com/jquery-1.11.1.min.js"></script>
    <!------ Include the above in your HEAD tag ---------->

    <link href="//netdna.bootstrapcdn.com/font-awesome/4.0.3/css/font-awesome.min.css" rel="stylesheet">
</head>
<body>
<div class="container">
    <div class="row">
        <div class="col-md-offset-2 col-md-8 col-lg-offset-3 col-lg-6">
            <div class="well profile">
                <div class="col-sm-12">
                    <div class="col-xs-12 col-sm-8">
                        <h2>Nicole Pearson</h2>
                        <p><strong>About: </strong> Web Designer / UI. </p>
                        <p><strong>Hobbies: </strong> Read, out with friends, listen to music, draw and learn new
                            things. </p>
                        <p><strong>Skills: </strong>
                            <span class="tags">html5</span>
                            <span class="tags">css3</span>
                            <span class="tags">jquery</span>
                            <span class="tags">bootstrap3</span>
                        </p>
                    </div>
                    <div class="col-xs-12 col-sm-4 text-center">
                        <figure>
                            <img src="http://www.localcrimenews.com/wp-content/uploads/2013/07/default-user-icon-profile.png"
                                 alt="" class="img-circle img-responsive">
                            <figcaption class="ratings">
                                <p>Ratings
                                    <a href="#">
                                        <span class="fa fa-star"></span>
                                    </a>
                                    <a href="#">
                                        <span class="fa fa-star"></span>
                                    </a>
                                    <a href="#">
                                        <span class="fa fa-star"></span>
                                    </a>
                                    <a href="#">
                                        <span class="fa fa-star"></span>
                                    </a>
                                    <a href="#">
                                        <span class="fa fa-star-o"></span>
                                    </a>
                                </p>
                            </figcaption>
                        </figure>
                    </div>
                </div>
                <div class="col-xs-12 divider text-center">
                    <div class="col-xs-12 col-sm-4 emphasis">
                        <h2><strong> 20,7K </strong></h2>
                        <p>
                            <small>Followers</small>
                        </p>
                        <button class="btn btn-success btn-block"><span class="fa fa-plus-circle"></span> Follow
                        </button>
                    </div>
                    <div class="col-xs-12 col-sm-4 emphasis">
                        <h2><strong>245</strong></h2>
                        <p>
                            <small>Following</small>
                        </p>
                        <button class="btn btn-info btn-block"><span class="fa fa-user"></span> View Profile</button>
                    </div>
                    <div class="col-xs-12 col-sm-4 emphasis">
                        <h2><strong>43</strong></h2>
                        <p>
                            <small>Snippets</small>
                        </p>
                        <div class="btn-group dropup btn-block">
                            <button type="button" class="btn btn-primary"><span class="fa fa-gear"></span> Options
                            </button>
                            <button type="button" class="btn btn-primary dropdown-toggle" data-toggle="dropdown">
                                <span class="caret"></span>
                                <span class="sr-only">Toggle Dropdown</span>
                            </button>
                            <ul class="dropdown-menu text-left" role="menu">
                                <li><a href="#"><span class="fa fa-envelope pull-right"></span> Send an email </a></li>
                                <li><a href="#"><span class="fa fa-list pull-right"></span> Add or remove from a list
                                </a></li>
                                <li class="divider"></li>
                                <li><a href="#"><span class="fa fa-warning pull-right"></span>Report this user for spam</a>
                                </li>
                                <li class="divider"></li>
                                <li><a href="#" class="btn disabled" role="button"> Unfollow </a></li>
                            </ul>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
</body>
</html>

detail/templates/detail/admin.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
    this is admin page
</body>
</html>

detail/templates/detail/blogdetail.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
    <h3> {{ blog.title }}</h3>
     {{ blog.description }}
</body>
</html>

detail/templates/detail/bloglist.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
{#    show the bloglist from table #}
        <table border="1">
             <tr>
                 <th> title </th>
                 <th>published date </th>
             </tr>
            {% for blog in bloglist %}
                <tr>
                    <td> <a href="{% url 'blogdetail' blog.id %}">{{ blog.title }}</a> </td>
                    <td>{{ blog.published_date }}</td>
                </tr>
            {% endfor %}
        </table>
</body>
</html>

detail/templates/detail/contact.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
    <style type="text/css">
        body {
            padding: 5%;
        }

    </style>

</head>
<body>
    <h3>Contact me</h3>
    <hr>
<form action="{% url 'contact' %}" method="post">
     {% csrf_token %}
    <div class="form-group">
        <label for="exampleInputEmail1">Email address</label>
        <input type="email" class="form-control" id="exampleInputEmail1" aria-describedby="emailHelp"
               placeholder="Enter email" name="email">
        <small id="emailHelp" class="form-text text-muted">We'll never share your email with anyone else.</small>
    </div>
    <div class="form-group">
        <label for="fullname">Full Name</label>
        <input type="text" class="form-control" id="fullname" placeholder="firstName lastName" name="fullname">
    </div>
    <input type="submit" class="btn btn-primary" value="Send Message">
</form>
</body>
</html>

detail/templates/detail/contactform.html
{% load bootstrap3 %}
<html>
<head>
    <script
            src="https://code.jquery.com/jquery-3.3.1.min.js"
            integrity="sha256-FgpCb/KJQlLNfOu91ta32o/NMZxltwRo8QtmkMRdAu8="
            crossorigin="anonymous"></script>
    <link href="//netdna.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap.min.css" rel="stylesheet" id="bootstrap-css">
    <style type="text/css">
        body {
            padding: 10px;
        }
    </style>
    <script>
        $(document).ready(function () {
            console.log("Page loaded");
            $("#id_write_message").change(function () {
               console.log($(this).prop('checked'));
                if($(this).prop('checked')){
                    // show messagebox
                    $("#id_message").show();
                } else {
                    // hide
                     $("#id_message").hide();
                }

            });
            $("#id_phone").change(function () {
                console.log($(this).val());
                var data = $("#id_phone").val();
                if(isNaN(data)){
                    alert("this is not number");
                }
            })
        });
    </script>
</head>
<body>
<form method="post" novalidate>
    {% csrf_token %}
    {% bootstrap_form form %}
    {#    <button type="submit">Submit</button>#}
    {% buttons %}
        <button type="submit" class="btn btn-primary">
            {% bootstrap_icon "star" %} Submit
        </button>
    {% endbuttons %}
</form>
</body>
</html>

detail/templates/detail/mywork.html
{% load static %}
<html>
<head>
    <title>My work</title>
    <link href="{% static 'css/mywork.css' %}" rel="stylesheet">
    <link href="//maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" rel="stylesheet" id="bootstrap-css">
    <script src="//maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js"></script>
    <script src="//cdnjs.cloudflare.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
    <!------ Include the above in your HEAD tag ---------->
</head>
<body>
<!-- Team -->
<section id="team" class="pb-5">
    <div class="container">
        <h5 class="section-title h1">MY WORK</h5>
        <div class="row">
            <!-- Team member -->
            {% for work in data %}
            <div class="col-xs-12 col-sm-6 col-md-4">
                <div class="image-flip" ontouchstart="this.classList.toggle('hover');">
                    <div class="mainflip">
                        <div class="frontside">
                            <div class="card">
                                <div class="card-body text-center">
                                    <p><img class=" img-fluid"
                                            src="/media/{{ work.image }}"
                                            alt="card image"></p>
                                    <h4 class="card-title">{{ work.title }}</h4>
                                    <p class="card-text">{{ work.description|slice:"0:50" }}...</p>
                                    <a href="#" class="btn btn-primary btn-sm"><i class="fa fa-plus"></i></a>
                                </div>
                            </div>
                        </div>
                        <div class="backside">
                            <div class="card">
                                <div class="card-body text-center mt-4">
                                    <h4 class="card-title">{{ work.title }}</h4>
                                    <p class="card-text">{{ work.description|slice:"0:50" }}...</p>
                                    <ul class="list-inline">
                                        <li class="list-inline-item">
                                            <a class="social-icon text-xs-center" target="_blank" href="{{ work.web_link }}">
                                                <i class="fa fa-facebook"></i>
                                            </a>
                                        </li>
                                        <li class="list-inline-item">
                                            <a class="social-icon text-xs-center" target="_blank" href="#">
                                                <i class="fa fa-twitter"></i>
                                            </a>
                                        </li>
                                        <li class="list-inline-item">
                                            <a class="social-icon text-xs-center" target="_blank" href="#">
                                                <i class="fa fa-skype"></i>
                                            </a>
                                        </li>
                                        <li class="list-inline-item">
                                            <a class="social-icon text-xs-center" target="_blank" href="#">
                                                <i class="fa fa-google"></i>
                                            </a>
                                        </li>
                                    </ul>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <!-- ./Team member -->
            {% endfor %}
        </div>
    </div>
</section>
<!-- Team -->
</body>
</html>